# Generated by Django 5.2.10 on 2026-03-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Doctor'), ('LAB_PROVIDER', 'Lab Provider'), ('ADMIN', 'Admin')], default='PATIENT', max_length=15),
        ),
    ]
