# Generated by Django 5.2.10 on 2026-03-12 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_tests', '0002_labproviderprofile_labtestoffering'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestcart',
            name='selected_lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='lab_tests.lab'),
        ),
    ]
