# Generated by Django 5.2.10 on 2026-01-19 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0002_alter_consultation_options_consultation_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255, unique=True)),
                ('room_sid', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('ACTIVE', 'Active'), ('ENDED', 'Ended')], default='WAITING', max_length=20)),
                ('patient_joined', models.BooleanField(default=False)),
                ('doctor_joined', models.BooleanField(default=False)),
                ('patient_joined_at', models.DateTimeField(blank=True, null=True)),
                ('doctor_joined_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_room', to='consultations.consultation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('ROOM_CREATED', 'Room Created'), ('PARTICIPANT_JOINED', 'Participant Joined'), ('PARTICIPANT_LEFT', 'Participant Left'), ('CALL_STARTED', 'Call Started'), ('CALL_ENDED', 'Call Ended'), ('ERROR', 'Error')], max_length=50)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('video_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='videocall.videoroom')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
