# Generated by Django 5.2.10 on 2026-01-19 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_alter_consultation_options_consultation_completed_at_and_more'),
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='available_days',
            field=models.CharField(default='Mon,Tue,Wed,Thu,Fri', max_length=50),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='available_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='available_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(choices=[('GENERAL', 'General Physician'), ('CARDIOLOGY', 'Cardiologist'), ('DERMATOLOGY', 'Dermatologist'), ('NEUROLOGY', 'Neurologist'), ('ORTHOPEDICS', 'Orthopedic'), ('PEDIATRICS', 'Pediatrician'), ('PSYCHIATRY', 'Psychiatrist'), ('GYNECOLOGY', 'Gynecologist'), ('ENT', 'ENT Specialist'), ('OPHTHALMOLOGY', 'Ophthalmologist'), ('DENTAL', 'Dentist'), ('OTHER', 'Other')], default='GENERAL', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DoctorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='consultations.consultation')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('doctor', 'patient', 'consultation')},
            },
        ),
    ]
